# Sat,  8 Oct 2016 14:06:42 +0200
timestamp = 1475928402

[netvars]
m_ArmorValue = 43512
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12208
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12320
m_aimPunchAngleVel = 12332
m_bGunGameImmunity = 14512
m_bHasDefuser = 43528
m_bHasHelmet = 43504
m_bInReload = 12869
m_bIsDefusing = 14500
m_bIsScoped = 14492
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12992
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 43620
m_iEntityQuality = 12172
m_iFOVStart = 12756
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iShotsFired = 41664
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13344
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13732
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12308

[signatures]
dwClientState = 6025908
dwClientState_GetLocalPlayer = 376
dwClientState_Map = 644
dwClientState_MapDirectory = 384
dwClientState_MaxPlayer = 776
dwClientState_PlayerInfo = 21052
dwClientState_State = 256
dwClientState_ViewAngles = 19724
dwEntityList = 78297540
dwForceAttack = 49199544
dwForceJump = 83109092
dwGameDir = 6673688
dwGlobalVars = 11002788
dwGlowObjectManager = 83635588
dwInput = 82797856
dwLocalPlayer = 11052348
dwPlayerResource = 49191924
dwRadarBase = 82708268
dwSensitivity = 11074884
dwSensitivityPtr = 11074840
dwViewMatrix = 78239076
dwWeaponTable = 82783116
dwWeaponTableIndex = 12912
dwZoomSensitivityRatioPtr = 11094560
dwbSendPackets = 922090
m_pStudioHdr = 10556
