# Wed, 30 Nov 2016 15:44:18 +0100
timestamp = 1480517058

[netvars]
m_ArmorValue = 43524
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14512
m_bHasDefuser = 43540
m_bHasHelmet = 43516
m_bInReload = 12869
m_bIsDefusing = 14500
m_bIsScoped = 14492
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12992
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 43632
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iShotsFired = 41664
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13348
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13736
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 6042308
dwClientState_GetLocalPlayer = 376
dwClientState_Map = 644
dwClientState_MapDirectory = 384
dwClientState_MaxPlayer = 776
dwClientState_PlayerInfo = 21052
dwClientState_State = 256
dwClientState_ViewAngles = 19724
dwEntityList = 78384292
dwForceAttack = 49286644
dwForceAttack2 = 49286608
dwForceBackward = 49286680
dwForceForward = 49286668
dwForceJump = 83195948
dwForceLeft = 49286584
dwForceRight = 49286596
dwGameDir = 6690200
dwGlobalVars = 11084704
dwGlowObjectManager = 83726788
dwInput = 82884592
dwInterfaceLinkList = 7467076
dwLocalPlayer = 11135176
dwPlayerResource = 49279016
dwRadarBase = 82795132
dwSensitivity = 11157684
dwSensitivityPtr = 11157640
dwViewMatrix = 78325828
dwWeaponTable = 82869884
dwWeaponTableIndex = 12912
dwYawPtr = 11157376
dwZoomSensitivityRatioPtr = 11177424
dwbSendPackets = 924362
m_pStudioHdr = 10556
