# Fri, 19 May 2017 11:30:30 +0200
timestamp = 1495186230

[netvars]
m_ArmorValue = 43524
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14512
m_bHasDefuser = 43540
m_bHasHelmet = 43516
m_bInReload = 12869
m_bIsDefusing = 14500
m_bIsScoped = 14492
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12992
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13184
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 43632
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13164
m_iShotsFired = 41664
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13348
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13736
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 5886228
dwClientState_GetLocalPlayer = 376
dwClientState_Map = 644
dwClientState_MapDirectory = 384
dwClientState_MaxPlayer = 776
dwClientState_PlayerInfo = 21052
dwClientState_State = 256
dwClientState_ViewAngles = 19724
dwEntityList = 78053748
dwForceAttack = 48965024
dwForceAttack2 = 48965036
dwForceBackward = 48965060
dwForceForward = 48965048
dwForceJump = 82866004
dwForceLeft = 48964964
dwForceRight = 48964976
dwGameDir = 6534864
dwGameRulesProxy = 83302508
dwGetAllClasses = 83302716
dwGlobalVars = 5885464
dwGlowObjectManager = 83414164
dwInput = 82554168
dwInterfaceLinkList = 7173284
dwLocalPlayer = 11095060
dwMouseEnable = 11117688
dwMouseEnablePtr = 11117640
dwPlayerResource = 48957660
dwRadarBase = 82464372
dwSensitivity = 11117332
dwSensitivityPtr = 11117288
dwSetClanTag = 552416
dwViewMatrix = 77995026
dwYawPtr = 11116760
dwZoomSensitivityRatioPtr = 11137256
dwbSendPackets = 836858
dwppDirect3DDevice9 = 642880
m_pStudioHdr = 10556
