# Wed,  7 Jun 2017 00:26:55 +0200
timestamp = 1496788015

[netvars]
m_ArmorValue = 45640
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14512
m_bHasDefuser = 45656
m_bHasHelmet = 45628
m_bInReload = 12869
m_bIsDefusing = 14500
m_bIsScoped = 14492
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12992
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13184
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 45748
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13164
m_iShotsFired = 41664
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13348
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13736
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 5894684
dwClientState_GetLocalPlayer = 376
dwClientState_IsHLTV = 19652
dwClientState_Map = 644
dwClientState_MapDirectory = 384
dwClientState_MaxPlayer = 776
dwClientState_PlayerInfo = 21052
dwClientState_State = 256
dwClientState_ViewAngles = 19724
dwEntityList = 78144548
dwForceAttack = 49055672
dwForceAttack2 = 49055684
dwForceBackward = 49055804
dwForceForward = 49055792
dwForceJump = 82957236
dwForceLeft = 49055768
dwForceRight = 49055780
dwGameDir = 6543312
dwGameRulesProxy = 83393756
dwGetAllClasses = 83393964
dwGlobalVars = 5893920
dwGlowObjectManager = 83506136
dwInput = 82645064
dwInterfaceLinkList = 7234372
dwLocalPlayer = 11181900
dwMouseEnable = 11204528
dwMouseEnablePtr = 11204480
dwPlayerResource = 49048380
dwRadarBase = 82555164
dwSensitivity = 11204172
dwSensitivityPtr = 11204128
dwSetClanTag = 553360
dwViewMatrix = 78085780
dwWeaponTable = 82630112
dwWeaponTableIndex = 12912
dwYawPtr = 11203600
dwZoomSensitivityRatioPtr = 11224184
dwbSendPackets = 837930
dwppDirect3DDevice9 = 642880
m_pStudioHdr = 10556
