# Mon, 14 Nov 2016 22:49:26 +0100
timestamp = 1479160166

[netvars]
m_ArmorValue = 43512
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14512
m_bHasDefuser = 43528
m_bHasHelmet = 43504
m_bInReload = 12869
m_bIsDefusing = 14500
m_bIsScoped = 14492
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12992
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 43620
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iShotsFired = 41664
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13348
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13736
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 6038212
dwClientState_GetLocalPlayer = 376
dwClientState_Map = 644
dwClientState_MapDirectory = 384
dwClientState_MaxPlayer = 776
dwClientState_PlayerInfo = 21052
dwClientState_State = 256
dwClientState_ViewAngles = 19724
dwEntityList = 78319508
dwForceAttack = 49221528
dwForceAttack2 = 49221444
dwForceBackward = 49221504
dwForceForward = 49221492
dwForceJump = 83131092
dwForceLeft = 49221468
dwForceRight = 49221480
dwGameDir = 6686104
dwGetAllClasses = 49214148
dwGlobalVars = 11023268
dwGlowObjectManager = 83659716
dwInput = 82819808
dwInterfaceLinkList = 7419668
dwLocalPlayer = 11072828
dwPlayerResource = 49213900
dwRadarBase = 82730348
dwSensitivity = 11095364
dwSensitivityPtr = 11095320
dwViewMatrix = 78261044
dwWeaponTable = 82805100
dwWeaponTableIndex = 12912
dwYawPtr = 11095056
dwZoomSensitivityRatioPtr = 11115040
dwbSendPackets = 924122
m_pStudioHdr = 10556
