timestamp = 1532596676

[signatures]
dwClientState = 5794420
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19656
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 784
dwClientState_PlayerInfo = 21056
dwClientState_State = 264
dwClientState_ViewAngles = 19728
dwEntityList = 78193636
dwForceAttack = 49104696
dwForceAttack2 = 49104708
dwForceBackward = 49104720
dwForceForward = 49104756
dwForceJump = 83019988
dwForceLeft = 49104732
dwForceRight = 49104792
dwGameDir = 6441960
dwGameRulesProxy = 83455084
dwGetAllClasses = 11385588
dwGlobalVars = 5793656
dwGlowObjectManager = 83631912
dwInput = 82694240
dwInterfaceLinkList = 7274692
dwLocalPlayer = 11234684
dwMouseEnable = 11257584
dwMouseEnablePtr = 11257536
dwPlayerResource = 49097404
dwRadarBase = 82604236
dwSensitivity = 11257228
dwSensitivityPtr = 11257184
dwSetClanTag = 558720
dwViewMatrix = 78134804
dwWeaponTable = 82696956
dwWeaponTableIndex = 12844
dwYawPtr = 11256656
dwZoomSensitivityRatioPtr = 11277328
dwbSendPackets = 854122
dwppDirect3DDevice9 = 667424
m_pStudioHdr = 10556
m_pitchClassPtr = 82604920
m_yawClassPtr = 11256656

[netvars]
m_ArmorValue = 45644
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12708
m_OriginalOwnerXuidLow = 12704
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14500
m_bHasDefuser = 45660
m_bHasHelmet = 45632
m_bInReload = 12917
m_bIsDefusing = 14488
m_bIsScoped = 14478
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_clrRender = 112
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 13024
m_fFlags = 256
m_flFallbackWear = 12720
m_flFlashDuration = 41736
m_flFlashMaxAlpha = 41732
m_flNextPrimaryAttack = 12808
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13152
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12216
m_iClip1 = 12852
m_iCompetitiveRanking = 6788
m_iCompetitiveWins = 7048
m_iCrosshairId = 45752
m_iEntityQuality = 12188
m_iFOVStart = 12760
m_iGlowIndex = 41760
m_iHealth = 252
m_iItemDefinitionIndex = 12186
m_iItemIDHigh = 12208
m_iObserverMode = 13132
m_iShotsFired = 41664
m_iState = 12840
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12712
m_nFallbackSeed = 12716
m_nFallbackStatTrak = 12724
m_nForceBone = 9852
m_nTickBase = 13316
m_rgflCoordinateFrame = 1088
m_szCustomName = 12332
m_szLastPlaceName = 13704
m_thirdPersonViewAngles = 12744
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304
