# Wed, 20 Dec 2017 13:20:54 +0100
timestamp = 1513772454

[netvars]
m_ArmorValue = 45624
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12204
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12652
m_OriginalOwnerXuidLow = 12648
m_aimPunchAngle = 12316
m_aimPunchAngleVel = 12328
m_bGunGameImmunity = 14484
m_bHasDefuser = 45640
m_bHasHelmet = 45612
m_bInReload = 12869
m_bIsDefusing = 14472
m_bIsScoped = 14462
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12976
m_fFlags = 256
m_flFallbackWear = 12664
m_flFlashDuration = 41720
m_flFlashMaxAlpha = 41716
m_flNextPrimaryAttack = 12760
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hObserverTarget = 13152
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12804
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 45732
m_iEntityQuality = 12172
m_iFOVStart = 12760
m_iGlowIndex = 41744
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iObserverMode = 13132
m_iShotsFired = 41648
m_iState = 12792
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12656
m_nFallbackSeed = 12660
m_nFallbackStatTrak = 12668
m_nForceBone = 9852
m_nTickBase = 13316
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13704
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12304

[signatures]
dwClientState = 5748716
dwClientState_GetLocalPlayer = 384
dwClientState_IsHLTV = 19656
dwClientState_Map = 652
dwClientState_MapDirectory = 392
dwClientState_MaxPlayer = 784
dwClientState_PlayerInfo = 21056
dwClientState_State = 264
dwClientState_ViewAngles = 19728
dwEntityList = 78089124
dwForceAttack = 49000292
dwForceAttack2 = 49000304
dwForceBackward = 49000268
dwForceForward = 49000256
dwForceJump = 82902540
dwForceLeft = 49000232
dwForceRight = 49000244
dwGameDir = 6393960
dwGameRulesProxy = 83337556
dwGetAllClasses = 83337764
dwGlobalVars = 5747952
dwGlowObjectManager = 83450352
dwInput = 82589544
dwInterfaceLinkList = 7186676
dwLocalPlayer = 11124188
dwMouseEnable = 11146816
dwMouseEnablePtr = 11146768
dwPlayerResource = 48992940
dwRadarBase = 82499740
dwSensitivity = 11146460
dwSensitivityPtr = 11146416
dwSetClanTag = 551376
dwViewMatrix = 78030356
dwWeaponTable = 82592612
dwWeaponTableIndex = 12796
dwYawPtr = 11145888
dwZoomSensitivityRatioPtr = 11166472
dwbSendPackets = 839002
dwppDirect3DDevice9 = 663360
m_pStudioHdr = 10556
